# Generated by Django 2.2.5 on 2019-10-01 10:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('carts', '0002_cart_some'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='some',
        ),
    ]
